hw01 - Lauren Park
cfss-sp20/hw01 pull request #48
Opened 2020-04-13 05:44 UTC by ljpark

For this first homework assignment, I wrote a brief introduction about myself using RMarkdown to insert various stylistic effects, a link, and an image. Firstly, I had to fork the homework assignment. It was stored in the repository, README.md, so I had to create my own personal copy of the assignment and could make changes to the repository. I then had to clone and make a local copy so I could open up the repository in RStudio and make the changes I desire. In order to get these changes successfully into the README.md, I had to save my file after each edit. After this, I clicked on the "Git" tab on the right side of the server. Once clicked, I pressed the "commit" button in order to stage and commit the file. This was important because I had to make modifications of multiple files during my homework process, so I want them all grouped together. In the commit message field before choosing the README.md, I added a little message of what I was committing. When I finished the commit step, I had to "push" these committed changes back into GitHub since they were not visible in the README.md yet. I had to click the small green arrow in the same section as the commit button. This button pushed the changes into GitHub. My final step to confirm that my changes were made, I went back to GitHub and refreshed my page. 

I found the workflow of GitHub to be initially daunting because of all the steps and things to remember to do. It took me a few tries in the beginning, where I found myself frustrated as I would go back to the GitHub and not see any changes in the repository. However, after a lot of trial and error, I got the swing of it. Once I figured out the steps, I was able to focus on the actual assignment which was way more enjoyable. It was a very fun and rewarding experience to see the changes I made in RStudio become visible when I clicked the refresh button on my GitHub page. The video tutorial on the course website about the Homework Work Flow was extremely helpful with getting me acquainted and used to the assignment. I would not have been able to do this project without this video. Additionally, the instruction manual to Markdown (linked on the HW01 page) was very helpful as well. I was able to learn the commands that would allow me to stylize my introduction and add cool features. The hardest part of the assignment was being introduced to the Work Flow system and committing/pushing changes from RStudio into GitHub. Also, it was challenging to learn the commands for certain things like images, lists, bold/italicized text, and headers. The easiest part was repeating the steps once I got them down!

2020-04-15 02:31 UTC, sarahcy1 commented
Hi Lauren, 

Good job overall! I really like the way you formatting your biography; I like that you pointed out some fun facts and introduced an amazing food blog to everybody(love it :)). You also did a great job in inserting the photo.

Evaluation
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |     X      |              |            |
| **Coding strategy**         |    X       |              |            |
| **Presentation**            |     X      |              |            |
| **Achievement, creativity** |    X       |              |            |
| **Reproducibility**         |     X      |              |            |


Cheers, 
Sara

2020-04-15 18:05 UTC, priemB commented on README.md
> +* Sitting on the quad when the weather is nice
Good use of the list syntax - makes it easier to understand the information.

2020-04-15 18:06 UTC, priemB commented on README.md
> +[Here is the link to one of my favorite food blog guides! Enjoy!:)](https://chicago.eater.com/2018/1/5/16151978/best-food-chicago-restaurants-city-guide)
It might make more sense to just hyperlink the [Here] section of that sentence, instead of making the whole section a hyperlink.

2020-04-15 18:06 UTC, priemB commented on README.md
> +Last but not least, here is a picture of the river. I think that West Loop is home to some of the **best food** in Chicago downtown! *(Picture is taken from hotspotrentals.com)*
Good use of **bold**

2020-04-15 18:07 UTC, priemB commented on README.md
> +### A Little Bit About Me!
The ##Headers help organize the information into easier to read sections.

2020-04-15 18:09 UTC, priemB commented on README.md
> +![](https://www.hotspotrentals.com/wp-content/uploads/2018/12/shot-of-West-Loop-1.jpg)
You could also add a link to the image. 

Code:

[![your image caption](image.png)](www.link_to_image.com)

2020-04-15 18:13 UTC, priemB commented on README.md
> +#### These are a few of *my favorite things* to do in Chicago:
You could just do the Italicized *My Favorite Things to do in Chicago* as the header (instead of having it be more of a sentence.

2020-04-15 18:14 UTC, priemB requested changes
This looks great! I've left the 3+ and 3 suggestions for the peer review.

2020-04-16 14:34 UTC, bensoltoff reviewed
Evaluation
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |           |          x    |            |
| **Coding strategy**         |           |         x     |            |
| **Presentation**            |           |          x    |            |
| **Achievement, creativity** |           |    x          |            |
| **Reproducibility**         |           |      x        |            |

* Covers several different Markdown elements
* Good practice of the homework workflow

2020-04-16 14:34 UTC, closed without merging